### ISSUE TITLE
ZIncrByParser bug

### ISSUE THREAD

**Issue by adrianyao89** [leonchen83/redis-replicator#12]
When I handle zincrby aof command, it occurred the exception.  
```
java.lang.NumberFormatException: For input string: "1.0"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.7.0_79]
	at java.lang.Integer.parseInt(Integer.java:492) ~[na:1.7.0_79]
	at java.lang.Integer.parseInt(Integer.java:527) ~[na:1.7.0_79]
	at com.moilioncircle.redis.replicator.cmd.parser.ZIncrByParser.parse(ZIncrByParser.java:31) ~[redis-replicator-2.0.0-rc2.jar:na]
	at com.moilioncircle.redis.replicator.cmd.parser.ZIncrByParser.parse(ZIncrByParser.java:25) ~[redis-replicator-2.0.0-rc2.jar:na]
	at com.moilioncircle.redis.replicator.RedisSocketReplicator.doOpen(RedisSocketReplicator.java:131) ~[redis-replicator-2.0.0-rc2.jar:na]
	at com.moilioncircle.redis.replicator.RedisSocketReplicator.open(RedisSocketReplicator.java:71) ~[redis-replicator-2.0.0-rc2.jar:na]
	at com.moilioncircle.redis.replicator.RedisReplicator.open(RedisReplicator.java:187) ~[redis-replicator-2.0.0-rc2.jar:na]
```

Redis version: 2.8.24
redis-replicator version: 1.X, 2.X

**Comment by leonchen83** [comment]
will fixed this issue in version 2.1.0.
legacy 1.0.x .please fixed this bug via self-defined command parser.
