### ISSUE TITLE
RDB EOFException

### ISSUE THREAD

**Issue by leonchen83** [leonchen83/redis-replicator#2]
https://git.oschina.net/leonchen83/redis-replicator/issues/2  

```
redis-replicator version : 1.0.6
```

``` java
RedisReplicator replicator = new RedisReplicator(new File("D:/dump.rdb"), Configuration.defaultSetting());
        replicator.addRdbFilter(kv -> kv.getKey().startsWith("mid_20000007_"));
        replicator.addRdbListener(new RdbListener.Adaptor() {
            @Override
            public void handle(Replicator replicator, KeyValuePair<?> kv) {
                System.out.println(kv);
            }
        });
        replicator.open();
```

``` java
Exception in thread "main" java.io.EOFException: end of file.
    at com.moilioncircle.redis.replicator.io.RedisInputStream.fill(RedisInputStream.java:191)
    at com.moilioncircle.redis.replicator.io.RedisInputStream.read(RedisInputStream.java:179)
    at com.moilioncircle.redis.replicator.io.RedisInputStream.fill(RedisInputStream.java:190)
    at com.moilioncircle.redis.replicator.io.RedisInputStream.read(RedisInputStream.java:179)
    at com.moilioncircle.redis.replicator.io.RedisInputStream.readBytes(RedisInputStream.java:90)
    at com.moilioncircle.redis.replicator.io.RedisInputStream.readString(RedisInputStream.java:162)
    at com.moilioncircle.redis.replicator.io.RedisInputStream.readString(RedisInputStream.java:158)
    at com.moilioncircle.redis.replicator.rdb.AbstractRdbParser$StringHelper.str(AbstractRdbParser.java:214)
    at com.moilioncircle.redis.replicator.rdb.AbstractRdbParser.rdbGenericLoadStringObject(AbstractRdbParser.java:162)
    at com.moilioncircle.redis.replicator.rdb.AbstractRdbParser.rdbLoadEncodedStringObject(AbstractRdbParser.java:178)
    at com.moilioncircle.redis.replicator.rdb.Rdb6Parser.rdbLoad(Rdb6Parser.java:60)
    at com.moilioncircle.redis.replicator.rdb.RdbParser.parse(RdbParser.java:104)
    at com.moilioncircle.redis.replicator.RedisFileReplicator.open(RedisFileReplicator.java:44)
    at com.moilioncircle.redis.replicator.RedisReplicator.open(RedisReplicator.java:144)
```

**Comment by leonchen83** [comment]
bug
fixed in version 1.0.7
