### ISSUE TITLE
请教一个效率问题

### ISSUE THREAD

**Issue by jiashiwen** [leonchen83/redis-replicator#26]
如果要在target端，使用连接池，但是sendCommand方法为proteced属性，那链接池需要自己来实现吗

**Comment by leonchen83** [comment]
是的， 需要自己实现，而且还要考虑一些细节问题，比如要记录最后一个`select db`的值，在从连接池里取得连接后，要执行一次`select db`, 保证在正确的db下执行命令

**Comment by leonchen83** [comment]
并且尽量用到redis 的pipeline功能， 一次发送多条命令， 加快速度

**Comment by jiashiwen** [comment]
刚刚测试了一下，大概一分钟5000多条，4k数据，但是不知道慢到哪儿了，就时用的咱们migration的例子

**Comment by leonchen83** [comment]
应该是慢在没用pipeline上了
因为redis的客户端是发送一条数据, 就同步等待返回结果. 网络利用率不太理想.
最好一次发送多条记录,然后再一次读取多条返回结果, 这样能充分利用网络带宽

**Comment by leonchen83** [comment]
可以试试这个
[Endpoint](https://github.com/leonchen83/redis-cli-tool/blob/master/src/main/java/com/moilioncircle/redis/cli/tool/net/Endpoint.java)然后测试一下

**Comment by jiashiwen** [comment]
检查了一下带宽问题，我进内网测试一下，回头把数据发上来

**Comment by jiashiwen** [comment]
不开pipeline也能达到美妙1000左右，只是在master压力达的时候报错
Exception in thread "main" java.net.ConnectException: 拒绝连接 (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.moilioncircle.redis.replicator.net.RedisSocketFactory.createSocket(RedisSocketFactory.java:80)
	at com.moilioncircle.redis.replicator.RedisSocketReplicator.connect(RedisSocketReplicator.java:291)
	at com.moilioncircle.redis.replicator.RedisSocketReplicator.establishConnection(RedisSocketReplicator.java:157)
	at com.moilioncircle.redis.replicator.RedisSocketReplicator$RedisSocketReplicatorRetrier.connect(RedisSocketReplicator.java:352)
	at com.moilioncircle.redis.replicator.AbstractReplicatorRetrier.retry(AbstractReplicatorRetrier.java:44)
	at com.moilioncircle.redis.replicator.RedisSocketReplicator.open(RedisSocketReplicator.java:91)
	at com.moilioncircle.redis.replicator.RedisReplicator.open(RedisReplicator.java:251)
	at red.shiwen.restredisreplicator.MigrationExample.sync(MigrationExample.java:150)
	at red.shiwen.restredisreplicator.MigrationExample.main(MigrationExample.java:62)

**Comment by jiashiwen** [comment]
不用pipeline可以达到1000每秒，挺不错的

**Comment by jiashiwen** [comment]
同步的时候有时候会停顿几秒后继续，没有任何报错

**Comment by leonchen83** [comment]
还是越快越好, 因为redis-replicator完全模拟slave, master-slave本质上是一个生产者消费者模式, 如果消费太慢, 并且生产者生产数据太快的话, 会使redis-server(生产者)内存耗尽
具体参见[5.2. 当出现EOFException](https://github.com/leonchen83/redis-replicator/blob/master/README.zh_CN.md#52-%E5%BD%93%E5%87%BA%E7%8E%B0eofexception)

**Comment by jiashiwen** [comment]
已经调整了redis.conf

**Comment by jiashiwen** [comment]
看了一下您写的Endpoint，用的时候时要单起一个现成，定时flush吗，不大了解咱们这个监听机制，监听到的命令写入pipe，然后定时flush，这样能够提升一些效率吗，不知道我理解的对不对啊

**Comment by leonchen83** [comment]
结合[MigrateRdbVisitor](https://github.com/leonchen83/redis-cli-tool/blob/master/src/main/java/com/moilioncircle/redis/cli/tool/ext/rmt/MigrateRdbVisitor.java)一起看, 这个Endpoint的batch方法作用是,每次只写入, 只有写入的count == pipe的时候, 才从InputStream中读结果, 简单来说是实现了redis 的pipeline

**Comment by jiashiwen** [comment]
ok

**Comment by leonchen83** [comment]
刚刚更新了下MigrateRdbVisitor, 注意下变更

**Comment by jiashiwen** [comment]
有没有办法只同步增量呢，比如我通过把rdb手动同步到从库，然后只同步增量，从库要通过公网，效率和可靠性都不好保障

**Comment by leonchen83** [comment]
第一次是一定会全量的, 之后断线重连后会走增量同步, 和slave行为一致

**Comment by jiashiwen** [comment]
明白了，所以最好把replicator部署在target一端，尽量的保障写入成功

**Comment by jiashiwen** [comment]
压力过大时还是会有java.io.EOFException: null，然后就同步不到东西了，benchmark性写入6G的数据

**Comment by leonchen83** [comment]
这是因为redis server的请求太大， 而事件消费太慢， 引起了redis的无限重连。

**Comment by leonchen83** [comment]
在压力过大的情况下，redis-server会主动断开同步慢的slave， 也会主动断开与redis-replicator的连接

**Comment by jiashiwen** [comment]
涨知识，多谢，我控制一下并发量试试
