### ISSUE TITLE
如何实现从某个点续传呢？我尝试这样实现抛出异常了

### ISSUE THREAD

**Issue by bisonliao** [leonchen83/redis-replicator#49]
```
        com.moilioncircle.redis.replicator.Configuration configuration = Configuration.defaultSetting();
        configuration.setReplOffset(215);
        configuration.setReplId("a1962b36d6a7bcf6b2fe660127bc3b4efbcd10ca");
        Replicator replicator = new RedisReplicator("119.2xxxx", 7001, configuration);

        replicator.addEventListener(new EventListener() {
            @Override
            public void onEvent(Replicator rep, Event event) {
```
异常：
```
Exception in thread "main" java.lang.AssertionError: expect [$,:,*,+,-] but: 
	at com.moilioncircle.redis.replicator.cmd.ReplyParser.parse(ReplyParser.java:174)
	at com.moilioncircle.redis.replicator.cmd.ReplyParser.parse(ReplyParser.java:58)
	at com.moilioncircle.redis.replicator.cmd.ReplyParser.parse(ReplyParser.java:53)
	at com.moilioncircle.redis.replicator.RedisSocketReplicator$RedisSocketReplicatorRetrier.open(RedisSocketReplicator.java:407)
	at com.moilioncircle.redis.replicator.AbstractReplicatorRetrier.retry(AbstractReplicatorRetrier.java:49)
	at com.moilioncircle.redis.replicator.RedisSocketReplicator.open(RedisSocketReplicator.java:111)
	at com.moilioncircle.redis.replicator.RedisReplicator.open(RedisReplicator.java:270)
	at com.company.Replica.main(Replica.java:76)

```
注释掉configuration.setReplicaID就ok，但会进行整个master库的同步

**Comment by leonchen83** [comment]
@bisonliao 
```
127.0.0.1:6379> info replication
# Replication
role:master
connected_slaves:1
slave0:ip=127.0.0.1,port=62744,state=online,offset=28,lag=1
master_failover_state:no-failover
master_replid:00874914772af73821a6c0b5470d5bc85a94e867
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:28
second_repl_offset:-1
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:1
repl_backlog_histlen:28
```

用`master_repl_offset:28`和`master_replid:00874914772af73821a6c0b5470d5bc85a94e867`

```
    public static void main(String[] args) throws Exception {
        final Replicator replicator = new RedisReplicator("redis://127.0.0.1:6379?replId=00874914772af73821a6c0b5470d5bc85a94e867&replOffset=28");
        replicator.addEventListener(new EventListener() {
            @Override
            public void onEvent(Replicator replicator, Event event) {
                System.out.println(event);
            }
        });

        replicator.open();
    }
```

**Comment by leonchen83** [comment]
如果随便设置一个offset的话，有可能那个offset不是增量命令的起始位置，导致解析失败

**Comment by bisonliao** [comment]
> 如果随便设置一个offset的话，有可能那个offset不是增量命令的起始位置，导致解析失败

我发现同一个master服务器的replication offset是不稳定的，两三天前有一个HSET命令是215开始，今天去看，首先是没有这个HSET了，似乎变成了KeyStringValueHash类型的数据同步，offset值也漂移了。

leon您能指教一下吗？

**Comment by leonchen83** [comment]
@bisonliao 
这是redis backlog机制决定的，增量的命令先缓存到backlog里，然后才会发给replicator，当有新的命令添加到backlog,并把旧的命令从backlog逐出时，相应的offset也会变化，当你用3天前的offset请求时，很可能在master里这个offset已经过期了，这时redis master认为你必须要重新全量同步，否则会丢失数据。这也就是为什么看到了KeyStringValueHash这种全量同步数据的原因。
