### ISSUE TITLE
Exception in parse redis command "set a 1010 px 1000"

### ISSUE THREAD

**Issue by yuz10** [leonchen83/redis-replicator#53]
```
ERROR parser value error: set a 1010 px 1000 {} (com.huawei.dms.connector.redis.parser.AbstractCommandParser:60)
java.lang.ClassCastException: java.lang.String cannot be cast to [B
        at com.moilioncircle.redis.replicator.util.Strings.toString(Strings.java:42)
        at com.moilioncircle.redis.replicator.util.Strings.toString(Strings.java:37)
        at com.moilioncircle.redis.replicator.cmd.CommandParsers.toRune(CommandParsers.java:34)
        at xxx
        at xxx
        at xxx
        at com.moilioncircle.redis.replicator.RedisSocketReplicator$RedisSocketReplicatorRetrier.open(RedisSocketReplicator.java:480)
        at com.moilioncircle.redis.replicator.AbstractReplicatorRetrier.retry(AbstractReplicatorRetrier.java:49)
        at com.moilioncircle.redis.replicator.RedisSocketReplicator.open(RedisSocketReplicator.java:123)
        at com.moilioncircle.redis.replicator.RedisReplicator.open(RedisReplicator.java:270)
        at xxx.DefaultRedisEventProcessor.lambda$startReplicatorAsync$0(DefaultRedisEventProcessor.java:313)
        at java.lang.Thread.run(Thread.java:748)
```

dependencies:

```
        <dependency>
            <groupId>com.moilioncircle</groupId>
            <artifactId>redis-replicator</artifactId>
            <version>3.6.0</version>
        </dependency>
       <dependency>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
            <version>2.9.0</version>
        </dependency>
```

**Comment by leonchen83** [comment]
@yuz10 
there is no `AbstractCommandParser` class in `redis-replicator`

**Comment by yuz10** [comment]
Sorry, it is my fault, I called toRune in my CommandParsers.

**Comment by leonchen83** [comment]
@yuz10 
 `CommandParsers.toRune(Object)` the argument type of Object must be `byte[]`

**Comment by yuz10** [comment]
Yes, actually, the bug happens here:

**Comment by leonchen83** [comment]
yes, that should be the root cause, you can create a PR to fix that issue. thanks
