### ISSUE TITLE
监听psync报错

### ISSUE THREAD

**Issue by Memorydoc** [leonchen83/redis-replicator#76]
通过监听psync 伪装为slave 监听master的命令
```         Replicator r = new RedisReplicator("redis://127.0.0.1:6379");
        r.addEventListener(new EventListener() {
            @Override
            public void onEvent(Replicator replicator, Event event) {
                System.out.println(event);
            }
        });
        
        r.open();
```
在执行到`r.open`后报错

```
Exception in thread "Thread-97" java.lang.OutOfMemoryError: Java heap space
	at com.moilioncircle.redis.replicator.util.ByteArray.<init>(ByteArray.java:62)
	at com.moilioncircle.redis.replicator.util.ByteArray.<init>(ByteArray.java:47)
	at com.moilioncircle.redis.replicator.io.RedisInputStream.readBytes(RedisInputStream.java:115)
	at com.moilioncircle.redis.replicator.rdb.BaseRdbParser$StringHelper.bytes(BaseRdbParser.java:295)
	at com.moilioncircle.redis.replicator.rdb.BaseRdbParser$StringHelper.listPackEntry(BaseRdbParser.java:411)
	at com.moilioncircle.redis.replicator.rdb.DefaultRdbValueVisitor.applyListQuickList2(DefaultRdbValueVisitor.java:429)
	at com.moilioncircle.redis.replicator.rdb.DefaultRdbVisitor.applyListQuickList2(DefaultRdbVisitor.java:474)
	at com.moilioncircle.redis.replicator.rdb.RdbParser.parse(RdbParser.java:267)
	at com.moilioncircle.redis.replicator.RedisSocketReplicator$1.handle(RedisSocketReplicator.java:178)
	at com.moilioncircle.redis.replicator.cmd.ReplyParser.parse(ReplyParser.java:103)
	at com.moilioncircle.redis.replicator.RedisSocketReplicator.reply(RedisSocketReplicator.java:349)
	at com.moilioncircle.redis.replicator.RedisSocketReplicator.parseDump(RedisSocketReplicator.java:166)
	at com.moilioncircle.redis.replicator.RedisSocketReplicator.trySync(RedisSocketReplicator.java:142)
	at com.moilioncircle.redis.replicator.RedisSocketReplicator$RedisSocketReplicatorRetrier.open(RedisSocketReplicator.java:440)
	at com.moilioncircle.redis.replicator.AbstractReplicatorRetrier.retry(AbstractReplicatorRetrier.java:49)
	at com.moilioncircle.redis.replicator.RedisSocketReplicator.open(RedisSocketReplicator.java:123)
```
是因为什么原因？ 内存不足吗

**Comment by leonchen83** [comment]
这个堆栈应该是list里存在大key或者很多大元素，用`ValueIterableRdbValueVisitor`将大key分片可以解决问题
